spring:
  jpa:
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.DefaultNamingStrategy
  datasource:
   username: postgres
   password: postgres
   url: jdbc:postgresql://localhost:5432/onetomany